development:
  adapter: mysql2
  encoding: utf8
  database: chordquiz_dev
  username: chordquiz
  password: password
  host: 127.0.0.1
  port: 3306
test:
  adapter: mysql2
  encoding: utf8
  database: chordquiz_test
  username: chordquiz
  password: password
  host: 127.0.0.1
  port: 3306